sonar.projectKey=Alex-MoraKy_proyecto1_seguridad
sonar.organization=alex-moraky
sonar.sources=plugins/python
sonar.exclusions=plugins/python/regress/**
sonar.sourceEncoding=UTF-8
sonar.python.version=3.11
